#! /usr/bin/env python
# encoding: utf-8

import os

def add_image (bld, category, name):
    icon_sizes = (16, 22, 24, 32, 48, 64, 128)
    
    for size in icon_sizes:
        format = str(size) + 'x' + str(size)
        srcfile = 'icons/hicolor/'+ format +'/'+ category +'/'+ name +'.png'
        
        if os.access (srcfile, os.F_OK):
            bld.install_files ('${DATADIR}/icons/hicolor/' + format + '/' + category,
                               srcfile)
    
    bld.install_files ('${DATADIR}/icons/hicolor/scalable/' + category,
                       'icons/hicolor/scalable/' + category +'/'+ name + '.svg')


def build(bld):
    bld.install_files('${DATADIR}/puzzle/ui', bld.path.ant_glob('ui/*.xml'))
    bld.install_files('${DATADIR}/puzzle/ui', bld.path.ant_glob('ui/*.ui'))

    add_image (bld, 'apps', 'puzzle')
    
    bld(features = 'subst',
        source= 'puzzle.desktop.in.in',
        target= 'puzzle.desktop.in',
        dict = bld.env
       )

    bld.add_group()

    bld(features = 'intltool_in',
        source   = 'puzzle.desktop.in',
        install_path = '${DATADIR}/applications',
        podir    = '../po',
        flags    = ['-d', '-q', '-u', '-c'])

